### ISSUE TITLE
LESS CSS compiler error

### ISSUE THREAD

**Issue by ivankolev** [acdvorak/intellij-lessc-plugin#12] opened 2012-10-30 03:38 UTC
IDEA spits this:
"file.less: java.io.IOException: No such file C:\Users\myusername\IdeaProjects\myproject\less\file.less"
 when trying to use the plugin. Maybe it's related to the patch Jetbrains pushed today, 11.1.4
I don't know what other info is needed, please advice

**Comment by acdvorak** [comment] 2012-10-30 16:34
Duplicate of #13 - merging issues

**Closed as completed by acdvorak** 2012-10-30 16:34 UTC
Labels: duplicate
